// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAsset = "Asset"

// Asset mapped from table <Asset>
type Asset struct {
	ID   int64  `gorm:"column:Id;primaryKey" json:"Id"`
	Name string `gorm:"column:Name;not null" json:"Name"`
}

// TableName Asset's table name
func (*Asset) TableName() string {
	return TableNameAsset
}
