// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCity = "City"

// City mapped from table <City>
type City struct {
	ID   int64  `gorm:"column:Id;primaryKey" json:"Id"`
	Name string `gorm:"column:Name;not null" json:"Name"`
}

// TableName City's table name
func (*City) TableName() string {
	return TableNameCity
}
