// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "Comment"

// Comment mapped from table <Comment>
type Comment struct {
	ID        int64     `gorm:"column:Id;primaryKey" json:"Id"`
	Text      string    `gorm:"column:Text" json:"Text"`
	UserID    int64     `gorm:"column:UserId" json:"UserId"`
	PunchID   int64     `gorm:"column:PunchId" json:"PunchId"`
	CreatedOn time.Time `gorm:"column:CreatedOn" json:"CreatedOn"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
