// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFacilityAsset = "FacilityAsset"

// FacilityAsset mapped from table <FacilityAsset>
type FacilityAsset struct {
	AssetID    int64     `gorm:"column:AssetId;primaryKey" json:"AssetId"`
	FacilityID int64     `gorm:"column:FacilityId;primaryKey" json:"FacilityId"`
	AddedOn    time.Time `gorm:"column:AddedOn" json:"AddedOn"`
}

// TableName FacilityAsset's table name
func (*FacilityAsset) TableName() string {
	return TableNameFacilityAsset
}
