// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFacility = "Facility"

// Facility mapped from table <Facility>
type Facility struct {
	ID        int64  `gorm:"column:Id;primaryKey" json:"Id"`
	Name      string `gorm:"column:Name;not null" json:"Name"`
	Address   string `gorm:"column:Address;not null" json:"Address"`
	ImageURL  string `gorm:"column:ImageUrl;not null" json:"ImageUrl"`
	CityID    int64  `gorm:"column:CityId;not null" json:"CityId"`
	CreatorID int64  `gorm:"column:CreatorId" json:"CreatorId"`
}

// TableName Facility's table name
func (*Facility) TableName() string {
	return TableNameFacility
}
