// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePunch = "Punch"

// Punch mapped from table <Punch>
type Punch struct {
	ID             int64     `gorm:"column:Id;primaryKey" json:"Id"`
	Title          string    `gorm:"column:Title;not null" json:"Title"`
	Description    string    `gorm:"column:Description;not null" json:"Description"`
	StartDate      time.Time `gorm:"column:StartDate;not null" json:"StartDate"`
	ExpirationDate time.Time `gorm:"column:ExpirationDate;not null" json:"ExpirationDate"`
	CoordX         []uint8   `gorm:"column:CoordX;not null" json:"CoordX"`
	CoordY         []uint8   `gorm:"column:CoordY;not null" json:"CoordY"`
	StatusID       int64     `gorm:"column:StatusId;not null" json:"StatusId"`
	AssigneeID     int64     `gorm:"column:AssigneeId" json:"AssigneeId"`
	CreatorID      int64     `gorm:"column:CreatorId;not null" json:"CreatorId"`
	SpaceID        int64     `gorm:"column:SpaceId;not null" json:"SpaceId"`
	AssetID        int64     `gorm:"column:AssetId" json:"AssetId"`
}

// TableName Punch's table name
func (*Punch) TableName() string {
	return TableNamePunch
}
