// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStatus = "Status"

// Status mapped from table <Status>
type Status struct {
	ID   int64  `gorm:"column:Id;primaryKey" json:"Id"`
	Name string `gorm:"column:Name;not null" json:"Name"`
}

// TableName Status's table name
func (*Status) TableName() string {
	return TableNameStatus
}
