// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID       int64   `gorm:"column:Id;primaryKey" json:"Id"`
	Name     string  `gorm:"column:Name;not null" json:"Name"`
	Password string  `gorm:"column:Password;not null" json:"Password"`
	Salt     []uint8 `gorm:"column:Salt" json:"Salt"`
	Email    string  `gorm:"column:Email;not null" json:"Email"`
	RoleID   int64   `gorm:"column:RoleId;not null" json:"RoleId"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
