// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"example/bluebean-go/model"
)

func newFacilityAsset(db *gorm.DB, opts ...gen.DOOption) facilityAsset {
	_facilityAsset := facilityAsset{}

	_facilityAsset.facilityAssetDo.UseDB(db, opts...)
	_facilityAsset.facilityAssetDo.UseModel(&model.FacilityAsset{})

	tableName := _facilityAsset.facilityAssetDo.TableName()
	_facilityAsset.ALL = field.NewAsterisk(tableName)
	_facilityAsset.AssetID = field.NewInt64(tableName, "AssetId")
	_facilityAsset.FacilityID = field.NewInt64(tableName, "FacilityId")
	_facilityAsset.AddedOn = field.NewTime(tableName, "AddedOn")

	_facilityAsset.fillFieldMap()

	return _facilityAsset
}

type facilityAsset struct {
	facilityAssetDo facilityAssetDo

	ALL        field.Asterisk
	AssetID    field.Int64
	FacilityID field.Int64
	AddedOn    field.Time

	fieldMap map[string]field.Expr
}

func (f facilityAsset) Table(newTableName string) *facilityAsset {
	f.facilityAssetDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f facilityAsset) As(alias string) *facilityAsset {
	f.facilityAssetDo.DO = *(f.facilityAssetDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *facilityAsset) updateTableName(table string) *facilityAsset {
	f.ALL = field.NewAsterisk(table)
	f.AssetID = field.NewInt64(table, "AssetId")
	f.FacilityID = field.NewInt64(table, "FacilityId")
	f.AddedOn = field.NewTime(table, "AddedOn")

	f.fillFieldMap()

	return f
}

func (f *facilityAsset) WithContext(ctx context.Context) *facilityAssetDo {
	return f.facilityAssetDo.WithContext(ctx)
}

func (f facilityAsset) TableName() string { return f.facilityAssetDo.TableName() }

func (f facilityAsset) Alias() string { return f.facilityAssetDo.Alias() }

func (f *facilityAsset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *facilityAsset) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 3)
	f.fieldMap["AssetId"] = f.AssetID
	f.fieldMap["FacilityId"] = f.FacilityID
	f.fieldMap["AddedOn"] = f.AddedOn
}

func (f facilityAsset) clone(db *gorm.DB) facilityAsset {
	f.facilityAssetDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f facilityAsset) replaceDB(db *gorm.DB) facilityAsset {
	f.facilityAssetDo.ReplaceDB(db)
	return f
}

type facilityAssetDo struct{ gen.DO }

func (f facilityAssetDo) Debug() *facilityAssetDo {
	return f.withDO(f.DO.Debug())
}

func (f facilityAssetDo) WithContext(ctx context.Context) *facilityAssetDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f facilityAssetDo) ReadDB() *facilityAssetDo {
	return f.Clauses(dbresolver.Read)
}

func (f facilityAssetDo) WriteDB() *facilityAssetDo {
	return f.Clauses(dbresolver.Write)
}

func (f facilityAssetDo) Session(config *gorm.Session) *facilityAssetDo {
	return f.withDO(f.DO.Session(config))
}

func (f facilityAssetDo) Clauses(conds ...clause.Expression) *facilityAssetDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f facilityAssetDo) Returning(value interface{}, columns ...string) *facilityAssetDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f facilityAssetDo) Not(conds ...gen.Condition) *facilityAssetDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f facilityAssetDo) Or(conds ...gen.Condition) *facilityAssetDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f facilityAssetDo) Select(conds ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f facilityAssetDo) Where(conds ...gen.Condition) *facilityAssetDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f facilityAssetDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *facilityAssetDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f facilityAssetDo) Order(conds ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f facilityAssetDo) Distinct(cols ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f facilityAssetDo) Omit(cols ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f facilityAssetDo) Join(table schema.Tabler, on ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f facilityAssetDo) LeftJoin(table schema.Tabler, on ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f facilityAssetDo) RightJoin(table schema.Tabler, on ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f facilityAssetDo) Group(cols ...field.Expr) *facilityAssetDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f facilityAssetDo) Having(conds ...gen.Condition) *facilityAssetDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f facilityAssetDo) Limit(limit int) *facilityAssetDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f facilityAssetDo) Offset(offset int) *facilityAssetDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f facilityAssetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *facilityAssetDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f facilityAssetDo) Unscoped() *facilityAssetDo {
	return f.withDO(f.DO.Unscoped())
}

func (f facilityAssetDo) Create(values ...*model.FacilityAsset) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f facilityAssetDo) CreateInBatches(values []*model.FacilityAsset, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f facilityAssetDo) Save(values ...*model.FacilityAsset) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f facilityAssetDo) First() (*model.FacilityAsset, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityAsset), nil
	}
}

func (f facilityAssetDo) Take() (*model.FacilityAsset, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityAsset), nil
	}
}

func (f facilityAssetDo) Last() (*model.FacilityAsset, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityAsset), nil
	}
}

func (f facilityAssetDo) Find() ([]*model.FacilityAsset, error) {
	result, err := f.DO.Find()
	return result.([]*model.FacilityAsset), err
}

func (f facilityAssetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FacilityAsset, err error) {
	buf := make([]*model.FacilityAsset, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f facilityAssetDo) FindInBatches(result *[]*model.FacilityAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f facilityAssetDo) Attrs(attrs ...field.AssignExpr) *facilityAssetDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f facilityAssetDo) Assign(attrs ...field.AssignExpr) *facilityAssetDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f facilityAssetDo) Joins(fields ...field.RelationField) *facilityAssetDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f facilityAssetDo) Preload(fields ...field.RelationField) *facilityAssetDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f facilityAssetDo) FirstOrInit() (*model.FacilityAsset, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityAsset), nil
	}
}

func (f facilityAssetDo) FirstOrCreate() (*model.FacilityAsset, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityAsset), nil
	}
}

func (f facilityAssetDo) FindByPage(offset int, limit int) (result []*model.FacilityAsset, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f facilityAssetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f facilityAssetDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f facilityAssetDo) Delete(models ...*model.FacilityAsset) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *facilityAssetDo) withDO(do gen.Dao) *facilityAssetDo {
	f.DO = *do.(*gen.DO)
	return f
}
