// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"example/bluebean-go/model"
)

func newFacilityUser(db *gorm.DB, opts ...gen.DOOption) facilityUser {
	_facilityUser := facilityUser{}

	_facilityUser.facilityUserDo.UseDB(db, opts...)
	_facilityUser.facilityUserDo.UseModel(&model.FacilityUser{})

	tableName := _facilityUser.facilityUserDo.TableName()
	_facilityUser.ALL = field.NewAsterisk(tableName)
	_facilityUser.FacilityID = field.NewInt64(tableName, "FacilityId")
	_facilityUser.UserID = field.NewInt64(tableName, "UserId")

	_facilityUser.fillFieldMap()

	return _facilityUser
}

type facilityUser struct {
	facilityUserDo facilityUserDo

	ALL        field.Asterisk
	FacilityID field.Int64
	UserID     field.Int64

	fieldMap map[string]field.Expr
}

func (f facilityUser) Table(newTableName string) *facilityUser {
	f.facilityUserDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f facilityUser) As(alias string) *facilityUser {
	f.facilityUserDo.DO = *(f.facilityUserDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *facilityUser) updateTableName(table string) *facilityUser {
	f.ALL = field.NewAsterisk(table)
	f.FacilityID = field.NewInt64(table, "FacilityId")
	f.UserID = field.NewInt64(table, "UserId")

	f.fillFieldMap()

	return f
}

func (f *facilityUser) WithContext(ctx context.Context) *facilityUserDo {
	return f.facilityUserDo.WithContext(ctx)
}

func (f facilityUser) TableName() string { return f.facilityUserDo.TableName() }

func (f facilityUser) Alias() string { return f.facilityUserDo.Alias() }

func (f *facilityUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *facilityUser) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 2)
	f.fieldMap["FacilityId"] = f.FacilityID
	f.fieldMap["UserId"] = f.UserID
}

func (f facilityUser) clone(db *gorm.DB) facilityUser {
	f.facilityUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f facilityUser) replaceDB(db *gorm.DB) facilityUser {
	f.facilityUserDo.ReplaceDB(db)
	return f
}

type facilityUserDo struct{ gen.DO }

func (f facilityUserDo) Debug() *facilityUserDo {
	return f.withDO(f.DO.Debug())
}

func (f facilityUserDo) WithContext(ctx context.Context) *facilityUserDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f facilityUserDo) ReadDB() *facilityUserDo {
	return f.Clauses(dbresolver.Read)
}

func (f facilityUserDo) WriteDB() *facilityUserDo {
	return f.Clauses(dbresolver.Write)
}

func (f facilityUserDo) Session(config *gorm.Session) *facilityUserDo {
	return f.withDO(f.DO.Session(config))
}

func (f facilityUserDo) Clauses(conds ...clause.Expression) *facilityUserDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f facilityUserDo) Returning(value interface{}, columns ...string) *facilityUserDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f facilityUserDo) Not(conds ...gen.Condition) *facilityUserDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f facilityUserDo) Or(conds ...gen.Condition) *facilityUserDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f facilityUserDo) Select(conds ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f facilityUserDo) Where(conds ...gen.Condition) *facilityUserDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f facilityUserDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *facilityUserDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f facilityUserDo) Order(conds ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f facilityUserDo) Distinct(cols ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f facilityUserDo) Omit(cols ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f facilityUserDo) Join(table schema.Tabler, on ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f facilityUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f facilityUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f facilityUserDo) Group(cols ...field.Expr) *facilityUserDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f facilityUserDo) Having(conds ...gen.Condition) *facilityUserDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f facilityUserDo) Limit(limit int) *facilityUserDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f facilityUserDo) Offset(offset int) *facilityUserDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f facilityUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *facilityUserDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f facilityUserDo) Unscoped() *facilityUserDo {
	return f.withDO(f.DO.Unscoped())
}

func (f facilityUserDo) Create(values ...*model.FacilityUser) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f facilityUserDo) CreateInBatches(values []*model.FacilityUser, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f facilityUserDo) Save(values ...*model.FacilityUser) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f facilityUserDo) First() (*model.FacilityUser, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityUser), nil
	}
}

func (f facilityUserDo) Take() (*model.FacilityUser, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityUser), nil
	}
}

func (f facilityUserDo) Last() (*model.FacilityUser, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityUser), nil
	}
}

func (f facilityUserDo) Find() ([]*model.FacilityUser, error) {
	result, err := f.DO.Find()
	return result.([]*model.FacilityUser), err
}

func (f facilityUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FacilityUser, err error) {
	buf := make([]*model.FacilityUser, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f facilityUserDo) FindInBatches(result *[]*model.FacilityUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f facilityUserDo) Attrs(attrs ...field.AssignExpr) *facilityUserDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f facilityUserDo) Assign(attrs ...field.AssignExpr) *facilityUserDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f facilityUserDo) Joins(fields ...field.RelationField) *facilityUserDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f facilityUserDo) Preload(fields ...field.RelationField) *facilityUserDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f facilityUserDo) FirstOrInit() (*model.FacilityUser, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityUser), nil
	}
}

func (f facilityUserDo) FirstOrCreate() (*model.FacilityUser, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FacilityUser), nil
	}
}

func (f facilityUserDo) FindByPage(offset int, limit int) (result []*model.FacilityUser, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f facilityUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f facilityUserDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f facilityUserDo) Delete(models ...*model.FacilityUser) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *facilityUserDo) withDO(do gen.Dao) *facilityUserDo {
	f.DO = *do.(*gen.DO)
	return f
}
